package visual.dynamic.described;

import io.ResourceFinder;

import java.awt.event.*;
import java.awt.geom.*;
import java.util.Iterator;

import javax.swing.SwingUtilities;

import visual.dynamic.described.*;
import visual.statik.TransformableContent;

/**
 * A blue colored bullet in the Top Down Shooter
 *
 * @author  Zachary Bolan
 * @version 11/13/13
 */
public class BlueBullet extends AbstractGameSprite
						implements Bullet
{
    private double     		radAngle, dx, dy;

    
    /**
     * Explicit Value Constructor
     *
     * @param content     The static visual content
     * @param startX	  The x location to be rendered at
     * @param startY	  The y location to be rendered at
     * @param mouseX	  The x location of the mouse
     * @param mouseY	  The y location of the mouse
     */
    public BlueBullet(TransformableContent content, ResourceFinder finder,
    				double startX, double startY,
                    double mouseX, double mouseY)
    {
    	super(content, finder);
    	init(startX, startY, mouseX, mouseY);
    	
    }
    
    public void doCollisions() {
    	
    			setSpeed(0);
    			setVisible(false);
    			isDestroyed = true;
    			reset();
    }
    

    synchronized public void init(double startX, double startY, double mouseX, double mouseY) {
    	
       	isDestroyed = false;
       	isAvailable = false;
    	
    	double				tx, ty, distance, rotateX, rotateY, rotAngle;
    	Rectangle2D         bounds;

        bounds = content.getBounds2D(false);
        x           = startX;
        y           = startY;
       
        this.dx = mouseX;
        this.dy = mouseY;
        
        setSpeed(10);
        antagonists.clear();

        // Set the initial rotation and location
   		tx = mouseX - x;
   		ty = mouseY - y;
   		distance = Math.sqrt(tx * tx + ty * ty);
   	
		rotateX = (tx / distance);
		rotateY = (ty / distance);
		rotAngle = rotateY/rotateX;

		radAngle = Math.atan2(rotAngle/rotateX, rotAngle/rotateY);
		setRotation(radAngle);
       	setLocation(x, y);
       	setVisible(true);
    }


    /**
     * Handle a tick event (generated by the Stage)
     * 
     * Move the location of the bullet and check for intersections
     *
     * @param time  The current time (which is not used)
     */
    public synchronized void handleTick(int time)
    {
    	if (!(this.isDestroyed)) {
    		
    		// Advance the position
    		x += speed * Math.cos(radAngle);
    		y += speed * Math.sin(radAngle);
    		setLocation(x, y);
    	
    		// 900 -100 700 -100
    		// Check if the bullet is "out-of-bounds"
    		if (x>900 || x<-100 || y>700 || y<-100) {
    			setSpeed(0);
    			setVisible(false);
    			isDestroyed = true;
    			reset();
    		}
    		
    	}	// end if isDestoryed
    		
    }  
    
}

